# Generated by Django 4.1.7 on 2023-03-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predictor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tweet', models.CharField(max_length=200)),
                ('is_hate_speech', models.IntegerField(max_length=1)),
                ('target_hs_individu', models.IntegerField(max_length=1)),
                ('target_hs_group', models.IntegerField(max_length=1)),
                ('type_hs_religion', models.IntegerField(max_length=1)),
                ('type_hs_ras', models.IntegerField(max_length=1)),
                ('type_hs_physical', models.IntegerField(max_length=1)),
                ('type_hs_gender', models.IntegerField(max_length=1)),
                ('type_hs_other', models.IntegerField(max_length=1)),
                ('level_hs_weak', models.IntegerField(max_length=1)),
            ],
        ),
    ]
