# Generated by Django 4.1.7 on 2023-03-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictor',
            name='level_hs_moderate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predictor',
            name='level_hs_strong',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predictor',
            name='is_hate_speech',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictor',
            name='level_hs_weak',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictor',
            name='target_hs_group',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictor',
            name='target_hs_individu',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictor',
            name='type_hs_gender',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictor',
            name='type_hs_other',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictor',
            name='type_hs_physical',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictor',
            name='type_hs_ras',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictor',
            name='type_hs_religion',
            field=models.IntegerField(),
        ),
    ]
